logging:
  config: classpath:${LOGBACK:logback-local.xml}
  level:
    root: info
    com:
      dionext: debug

web-config:
  multiSites:
    hiking:
      siteStaticStoragePath: "file:I:/doc/sites/hiking/output"
      siteStoragePaths:
        - "file:R:/doc/sites/hiking/input"
      siteInternalStoragePaths:
        - "file:I:/doc/sites/hiking/mediainfo"
