/*
 * Wikibase REST API
 * OpenAPI definition of Wikibase REST API
 *
 * The version of the OpenAPI document: 1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dionext.wikibase.client.api;

import com.dionext.wikibase.client.ApiCallback;
import com.dionext.wikibase.client.ApiClient;
import com.dionext.wikibase.client.ApiException;
import com.dionext.wikibase.client.ApiResponse;
import com.dionext.wikibase.client.Configuration;
import com.dionext.wikibase.client.Pair;

import com.google.gson.reflect.TypeToken;


import com.dionext.wikibase.client.model.AddItemRequestAllOfItemSitelinksValue;
import com.dionext.wikibase.client.model.DeleteSitelinkRequest;
import com.dionext.wikibase.client.model.PatchItemRequest;
import com.dionext.wikibase.client.model.SetSitelinkRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class SitelinksApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public SitelinksApi() {
        this(Configuration.getDefaultApiClient());
    }

    public SitelinksApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for deleteSitelink
     * @param itemId The ID of the required Item (required)
     * @param siteId The ID of the required Site (required)
     * @param ifNoneMatch Conditionally perform the request only if the resource has been modified since the specified entity revision numbers (optional)
     * @param ifModifiedSince Conditionally perform the request only if the resource has been modified after the specified date (optional)
     * @param ifMatch Conditionally perform the request only if the resource has not been modified since one of the specified entity revision numbers (optional)
     * @param ifUnmodifiedSince Conditionally perform the request only if the resource has not been modified after the specified date (optional)
     * @param authorization Make authenticated request using a provided bearer token (optional)
     * @param deleteSitelinkRequest Edit payload containing edit metadata (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The resource was deleted </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  * X-Authenticated-User - Optional username of the user making the request <br>  </td></tr>
        <tr><td> 400 </td><td> The request cannot be processed </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 403 </td><td> The access to resource was denied </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 404 </td><td> The specified resource was not found </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 409 </td><td> The specified Item was redirected </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 412 </td><td> The condition defined by a conditional request header is not fulfilled </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Too many requests </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 500 </td><td> An unexpected error has occurred </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
     </table>
     */
    public okhttp3.Call deleteSitelinkCall(String itemId, String siteId, List<String> ifNoneMatch, String ifModifiedSince, List<String> ifMatch, String ifUnmodifiedSince, String authorization, DeleteSitelinkRequest deleteSitelinkRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = deleteSitelinkRequest;

        // create path and map variables
        String localVarPath = "/entities/items/{item_id}/sitelinks/{site_id}"
            .replace("{" + "item_id" + "}", localVarApiClient.escapeString(itemId.toString()))
            .replace("{" + "site_id" + "}", localVarApiClient.escapeString(siteId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (ifNoneMatch != null) {
            localVarHeaderParams.put("If-None-Match", localVarApiClient.parameterToString(ifNoneMatch));
        }


        if (ifModifiedSince != null) {
            localVarHeaderParams.put("If-Modified-Since", localVarApiClient.parameterToString(ifModifiedSince));
        }


        if (ifMatch != null) {
            localVarHeaderParams.put("If-Match", localVarApiClient.parameterToString(ifMatch));
        }


        if (ifUnmodifiedSince != null) {
            localVarHeaderParams.put("If-Unmodified-Since", localVarApiClient.parameterToString(ifUnmodifiedSince));
        }


        if (authorization != null) {
            localVarHeaderParams.put("Authorization", localVarApiClient.parameterToString(authorization));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteSitelinkValidateBeforeCall(String itemId, String siteId, List<String> ifNoneMatch, String ifModifiedSince, List<String> ifMatch, String ifUnmodifiedSince, String authorization, DeleteSitelinkRequest deleteSitelinkRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'itemId' is set
        if (itemId == null) {
            throw new ApiException("Missing the required parameter 'itemId' when calling deleteSitelink(Async)");
        }

        // verify the required parameter 'siteId' is set
        if (siteId == null) {
            throw new ApiException("Missing the required parameter 'siteId' when calling deleteSitelink(Async)");
        }

        return deleteSitelinkCall(itemId, siteId, ifNoneMatch, ifModifiedSince, ifMatch, ifUnmodifiedSince, authorization, deleteSitelinkRequest, _callback);

    }

    /**
     * Delete an Item&#39;s Sitelink
     * 
     * @param itemId The ID of the required Item (required)
     * @param siteId The ID of the required Site (required)
     * @param ifNoneMatch Conditionally perform the request only if the resource has been modified since the specified entity revision numbers (optional)
     * @param ifModifiedSince Conditionally perform the request only if the resource has been modified after the specified date (optional)
     * @param ifMatch Conditionally perform the request only if the resource has not been modified since one of the specified entity revision numbers (optional)
     * @param ifUnmodifiedSince Conditionally perform the request only if the resource has not been modified after the specified date (optional)
     * @param authorization Make authenticated request using a provided bearer token (optional)
     * @param deleteSitelinkRequest Edit payload containing edit metadata (optional)
     * @return String
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The resource was deleted </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  * X-Authenticated-User - Optional username of the user making the request <br>  </td></tr>
        <tr><td> 400 </td><td> The request cannot be processed </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 403 </td><td> The access to resource was denied </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 404 </td><td> The specified resource was not found </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 409 </td><td> The specified Item was redirected </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 412 </td><td> The condition defined by a conditional request header is not fulfilled </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Too many requests </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 500 </td><td> An unexpected error has occurred </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
     </table>
     */
    public String deleteSitelink(String itemId, String siteId, List<String> ifNoneMatch, String ifModifiedSince, List<String> ifMatch, String ifUnmodifiedSince, String authorization, DeleteSitelinkRequest deleteSitelinkRequest) throws ApiException {
        ApiResponse<String> localVarResp = deleteSitelinkWithHttpInfo(itemId, siteId, ifNoneMatch, ifModifiedSince, ifMatch, ifUnmodifiedSince, authorization, deleteSitelinkRequest);
        return localVarResp.getData();
    }

    /**
     * Delete an Item&#39;s Sitelink
     * 
     * @param itemId The ID of the required Item (required)
     * @param siteId The ID of the required Site (required)
     * @param ifNoneMatch Conditionally perform the request only if the resource has been modified since the specified entity revision numbers (optional)
     * @param ifModifiedSince Conditionally perform the request only if the resource has been modified after the specified date (optional)
     * @param ifMatch Conditionally perform the request only if the resource has not been modified since one of the specified entity revision numbers (optional)
     * @param ifUnmodifiedSince Conditionally perform the request only if the resource has not been modified after the specified date (optional)
     * @param authorization Make authenticated request using a provided bearer token (optional)
     * @param deleteSitelinkRequest Edit payload containing edit metadata (optional)
     * @return ApiResponse&lt;String&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The resource was deleted </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  * X-Authenticated-User - Optional username of the user making the request <br>  </td></tr>
        <tr><td> 400 </td><td> The request cannot be processed </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 403 </td><td> The access to resource was denied </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 404 </td><td> The specified resource was not found </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 409 </td><td> The specified Item was redirected </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 412 </td><td> The condition defined by a conditional request header is not fulfilled </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Too many requests </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 500 </td><td> An unexpected error has occurred </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
     </table>
     */
    public ApiResponse<String> deleteSitelinkWithHttpInfo(String itemId, String siteId, List<String> ifNoneMatch, String ifModifiedSince, List<String> ifMatch, String ifUnmodifiedSince, String authorization, DeleteSitelinkRequest deleteSitelinkRequest) throws ApiException {
        okhttp3.Call localVarCall = deleteSitelinkValidateBeforeCall(itemId, siteId, ifNoneMatch, ifModifiedSince, ifMatch, ifUnmodifiedSince, authorization, deleteSitelinkRequest, null);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Delete an Item&#39;s Sitelink (asynchronously)
     * 
     * @param itemId The ID of the required Item (required)
     * @param siteId The ID of the required Site (required)
     * @param ifNoneMatch Conditionally perform the request only if the resource has been modified since the specified entity revision numbers (optional)
     * @param ifModifiedSince Conditionally perform the request only if the resource has been modified after the specified date (optional)
     * @param ifMatch Conditionally perform the request only if the resource has not been modified since one of the specified entity revision numbers (optional)
     * @param ifUnmodifiedSince Conditionally perform the request only if the resource has not been modified after the specified date (optional)
     * @param authorization Make authenticated request using a provided bearer token (optional)
     * @param deleteSitelinkRequest Edit payload containing edit metadata (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The resource was deleted </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  * X-Authenticated-User - Optional username of the user making the request <br>  </td></tr>
        <tr><td> 400 </td><td> The request cannot be processed </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 403 </td><td> The access to resource was denied </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 404 </td><td> The specified resource was not found </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 409 </td><td> The specified Item was redirected </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 412 </td><td> The condition defined by a conditional request header is not fulfilled </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Too many requests </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 500 </td><td> An unexpected error has occurred </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
     </table>
     */
    public okhttp3.Call deleteSitelinkAsync(String itemId, String siteId, List<String> ifNoneMatch, String ifModifiedSince, List<String> ifMatch, String ifUnmodifiedSince, String authorization, DeleteSitelinkRequest deleteSitelinkRequest, final ApiCallback<String> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteSitelinkValidateBeforeCall(itemId, siteId, ifNoneMatch, ifModifiedSince, ifMatch, ifUnmodifiedSince, authorization, deleteSitelinkRequest, _callback);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getSitelink
     * @param itemId The ID of the required Item (required)
     * @param siteId The ID of the required Site (required)
     * @param ifNoneMatch Conditionally perform the request only if the resource has been modified since the specified entity revision numbers (optional)
     * @param ifModifiedSince Conditionally perform the request only if the resource has been modified after the specified date (optional)
     * @param ifMatch Conditionally perform the request only if the resource has not been modified since one of the specified entity revision numbers (optional)
     * @param ifUnmodifiedSince Conditionally perform the request only if the resource has not been modified after the specified date (optional)
     * @param authorization Make authenticated request using a provided bearer token (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A Sitelink by Item id </td><td>  * ETag - Last entity revision number <br>  * Last-Modified - Last modified date <br>  * X-Authenticated-User - Optional username of the user making the request <br>  </td></tr>
        <tr><td> 304 </td><td> The specified resource has not been modified since last provided revision number or date </td><td>  * ETag - Last entity revision number <br>  </td></tr>
        <tr><td> 308 </td><td> The specified resource has permanently moved to the indicated location </td><td>  * Location - The URI of the newly created Statement <br>  </td></tr>
        <tr><td> 400 </td><td> The request cannot be processed </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 404 </td><td> The specified resource was not found </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 412 </td><td> The condition defined by a conditional request header is not fulfilled </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> An unexpected error has occurred </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
     </table>
     */
    public okhttp3.Call getSitelinkCall(String itemId, String siteId, List<String> ifNoneMatch, String ifModifiedSince, List<String> ifMatch, String ifUnmodifiedSince, String authorization, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/entities/items/{item_id}/sitelinks/{site_id}"
            .replace("{" + "item_id" + "}", localVarApiClient.escapeString(itemId.toString()))
            .replace("{" + "site_id" + "}", localVarApiClient.escapeString(siteId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (ifNoneMatch != null) {
            localVarHeaderParams.put("If-None-Match", localVarApiClient.parameterToString(ifNoneMatch));
        }


        if (ifModifiedSince != null) {
            localVarHeaderParams.put("If-Modified-Since", localVarApiClient.parameterToString(ifModifiedSince));
        }


        if (ifMatch != null) {
            localVarHeaderParams.put("If-Match", localVarApiClient.parameterToString(ifMatch));
        }


        if (ifUnmodifiedSince != null) {
            localVarHeaderParams.put("If-Unmodified-Since", localVarApiClient.parameterToString(ifUnmodifiedSince));
        }


        if (authorization != null) {
            localVarHeaderParams.put("Authorization", localVarApiClient.parameterToString(authorization));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getSitelinkValidateBeforeCall(String itemId, String siteId, List<String> ifNoneMatch, String ifModifiedSince, List<String> ifMatch, String ifUnmodifiedSince, String authorization, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'itemId' is set
        if (itemId == null) {
            throw new ApiException("Missing the required parameter 'itemId' when calling getSitelink(Async)");
        }

        // verify the required parameter 'siteId' is set
        if (siteId == null) {
            throw new ApiException("Missing the required parameter 'siteId' when calling getSitelink(Async)");
        }

        return getSitelinkCall(itemId, siteId, ifNoneMatch, ifModifiedSince, ifMatch, ifUnmodifiedSince, authorization, _callback);

    }

    /**
     * Retrieve an Item&#39;s Sitelink
     * 
     * @param itemId The ID of the required Item (required)
     * @param siteId The ID of the required Site (required)
     * @param ifNoneMatch Conditionally perform the request only if the resource has been modified since the specified entity revision numbers (optional)
     * @param ifModifiedSince Conditionally perform the request only if the resource has been modified after the specified date (optional)
     * @param ifMatch Conditionally perform the request only if the resource has not been modified since one of the specified entity revision numbers (optional)
     * @param ifUnmodifiedSince Conditionally perform the request only if the resource has not been modified after the specified date (optional)
     * @param authorization Make authenticated request using a provided bearer token (optional)
     * @return AddItemRequestAllOfItemSitelinksValue
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A Sitelink by Item id </td><td>  * ETag - Last entity revision number <br>  * Last-Modified - Last modified date <br>  * X-Authenticated-User - Optional username of the user making the request <br>  </td></tr>
        <tr><td> 304 </td><td> The specified resource has not been modified since last provided revision number or date </td><td>  * ETag - Last entity revision number <br>  </td></tr>
        <tr><td> 308 </td><td> The specified resource has permanently moved to the indicated location </td><td>  * Location - The URI of the newly created Statement <br>  </td></tr>
        <tr><td> 400 </td><td> The request cannot be processed </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 404 </td><td> The specified resource was not found </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 412 </td><td> The condition defined by a conditional request header is not fulfilled </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> An unexpected error has occurred </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
     </table>
     */
    public AddItemRequestAllOfItemSitelinksValue getSitelink(String itemId, String siteId, List<String> ifNoneMatch, String ifModifiedSince, List<String> ifMatch, String ifUnmodifiedSince, String authorization) throws ApiException {
        ApiResponse<AddItemRequestAllOfItemSitelinksValue> localVarResp = getSitelinkWithHttpInfo(itemId, siteId, ifNoneMatch, ifModifiedSince, ifMatch, ifUnmodifiedSince, authorization);
        return localVarResp.getData();
    }

    /**
     * Retrieve an Item&#39;s Sitelink
     * 
     * @param itemId The ID of the required Item (required)
     * @param siteId The ID of the required Site (required)
     * @param ifNoneMatch Conditionally perform the request only if the resource has been modified since the specified entity revision numbers (optional)
     * @param ifModifiedSince Conditionally perform the request only if the resource has been modified after the specified date (optional)
     * @param ifMatch Conditionally perform the request only if the resource has not been modified since one of the specified entity revision numbers (optional)
     * @param ifUnmodifiedSince Conditionally perform the request only if the resource has not been modified after the specified date (optional)
     * @param authorization Make authenticated request using a provided bearer token (optional)
     * @return ApiResponse&lt;AddItemRequestAllOfItemSitelinksValue&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A Sitelink by Item id </td><td>  * ETag - Last entity revision number <br>  * Last-Modified - Last modified date <br>  * X-Authenticated-User - Optional username of the user making the request <br>  </td></tr>
        <tr><td> 304 </td><td> The specified resource has not been modified since last provided revision number or date </td><td>  * ETag - Last entity revision number <br>  </td></tr>
        <tr><td> 308 </td><td> The specified resource has permanently moved to the indicated location </td><td>  * Location - The URI of the newly created Statement <br>  </td></tr>
        <tr><td> 400 </td><td> The request cannot be processed </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 404 </td><td> The specified resource was not found </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 412 </td><td> The condition defined by a conditional request header is not fulfilled </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> An unexpected error has occurred </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
     </table>
     */
    public ApiResponse<AddItemRequestAllOfItemSitelinksValue> getSitelinkWithHttpInfo(String itemId, String siteId, List<String> ifNoneMatch, String ifModifiedSince, List<String> ifMatch, String ifUnmodifiedSince, String authorization) throws ApiException {
        okhttp3.Call localVarCall = getSitelinkValidateBeforeCall(itemId, siteId, ifNoneMatch, ifModifiedSince, ifMatch, ifUnmodifiedSince, authorization, null);
        Type localVarReturnType = new TypeToken<AddItemRequestAllOfItemSitelinksValue>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Retrieve an Item&#39;s Sitelink (asynchronously)
     * 
     * @param itemId The ID of the required Item (required)
     * @param siteId The ID of the required Site (required)
     * @param ifNoneMatch Conditionally perform the request only if the resource has been modified since the specified entity revision numbers (optional)
     * @param ifModifiedSince Conditionally perform the request only if the resource has been modified after the specified date (optional)
     * @param ifMatch Conditionally perform the request only if the resource has not been modified since one of the specified entity revision numbers (optional)
     * @param ifUnmodifiedSince Conditionally perform the request only if the resource has not been modified after the specified date (optional)
     * @param authorization Make authenticated request using a provided bearer token (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A Sitelink by Item id </td><td>  * ETag - Last entity revision number <br>  * Last-Modified - Last modified date <br>  * X-Authenticated-User - Optional username of the user making the request <br>  </td></tr>
        <tr><td> 304 </td><td> The specified resource has not been modified since last provided revision number or date </td><td>  * ETag - Last entity revision number <br>  </td></tr>
        <tr><td> 308 </td><td> The specified resource has permanently moved to the indicated location </td><td>  * Location - The URI of the newly created Statement <br>  </td></tr>
        <tr><td> 400 </td><td> The request cannot be processed </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 404 </td><td> The specified resource was not found </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 412 </td><td> The condition defined by a conditional request header is not fulfilled </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> An unexpected error has occurred </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
     </table>
     */
    public okhttp3.Call getSitelinkAsync(String itemId, String siteId, List<String> ifNoneMatch, String ifModifiedSince, List<String> ifMatch, String ifUnmodifiedSince, String authorization, final ApiCallback<AddItemRequestAllOfItemSitelinksValue> _callback) throws ApiException {

        okhttp3.Call localVarCall = getSitelinkValidateBeforeCall(itemId, siteId, ifNoneMatch, ifModifiedSince, ifMatch, ifUnmodifiedSince, authorization, _callback);
        Type localVarReturnType = new TypeToken<AddItemRequestAllOfItemSitelinksValue>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getSitelinks
     * @param itemId The ID of the required Item (required)
     * @param ifNoneMatch Conditionally perform the request only if the resource has been modified since the specified entity revision numbers (optional)
     * @param ifModifiedSince Conditionally perform the request only if the resource has been modified after the specified date (optional)
     * @param ifMatch Conditionally perform the request only if the resource has not been modified since one of the specified entity revision numbers (optional)
     * @param ifUnmodifiedSince Conditionally perform the request only if the resource has not been modified after the specified date (optional)
     * @param authorization Make authenticated request using a provided bearer token (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of Sitelinks by Item id </td><td>  * ETag - Last entity revision number <br>  * Last-Modified - Last modified date <br>  * X-Authenticated-User - Optional username of the user making the request <br>  </td></tr>
        <tr><td> 304 </td><td> The specified resource has not been modified since last provided revision number or date </td><td>  * ETag - Last entity revision number <br>  </td></tr>
        <tr><td> 308 </td><td> The specified resource has permanently moved to the indicated location </td><td>  * Location - The URI of the newly created Statement <br>  </td></tr>
        <tr><td> 400 </td><td> The request cannot be processed </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 404 </td><td> The specified resource was not found </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 412 </td><td> The condition defined by a conditional request header is not fulfilled </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> An unexpected error has occurred </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
     </table>
     */
    public okhttp3.Call getSitelinksCall(String itemId, List<String> ifNoneMatch, String ifModifiedSince, List<String> ifMatch, String ifUnmodifiedSince, String authorization, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/entities/items/{item_id}/sitelinks"
            .replace("{" + "item_id" + "}", localVarApiClient.escapeString(itemId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (ifNoneMatch != null) {
            localVarHeaderParams.put("If-None-Match", localVarApiClient.parameterToString(ifNoneMatch));
        }


        if (ifModifiedSince != null) {
            localVarHeaderParams.put("If-Modified-Since", localVarApiClient.parameterToString(ifModifiedSince));
        }


        if (ifMatch != null) {
            localVarHeaderParams.put("If-Match", localVarApiClient.parameterToString(ifMatch));
        }


        if (ifUnmodifiedSince != null) {
            localVarHeaderParams.put("If-Unmodified-Since", localVarApiClient.parameterToString(ifUnmodifiedSince));
        }


        if (authorization != null) {
            localVarHeaderParams.put("Authorization", localVarApiClient.parameterToString(authorization));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getSitelinksValidateBeforeCall(String itemId, List<String> ifNoneMatch, String ifModifiedSince, List<String> ifMatch, String ifUnmodifiedSince, String authorization, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'itemId' is set
        if (itemId == null) {
            throw new ApiException("Missing the required parameter 'itemId' when calling getSitelinks(Async)");
        }

        return getSitelinksCall(itemId, ifNoneMatch, ifModifiedSince, ifMatch, ifUnmodifiedSince, authorization, _callback);

    }

    /**
     * Retrieve an Item&#39;s Sitelinks
     * 
     * @param itemId The ID of the required Item (required)
     * @param ifNoneMatch Conditionally perform the request only if the resource has been modified since the specified entity revision numbers (optional)
     * @param ifModifiedSince Conditionally perform the request only if the resource has been modified after the specified date (optional)
     * @param ifMatch Conditionally perform the request only if the resource has not been modified since one of the specified entity revision numbers (optional)
     * @param ifUnmodifiedSince Conditionally perform the request only if the resource has not been modified after the specified date (optional)
     * @param authorization Make authenticated request using a provided bearer token (optional)
     * @return Map&lt;String, AddItemRequestAllOfItemSitelinksValue&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of Sitelinks by Item id </td><td>  * ETag - Last entity revision number <br>  * Last-Modified - Last modified date <br>  * X-Authenticated-User - Optional username of the user making the request <br>  </td></tr>
        <tr><td> 304 </td><td> The specified resource has not been modified since last provided revision number or date </td><td>  * ETag - Last entity revision number <br>  </td></tr>
        <tr><td> 308 </td><td> The specified resource has permanently moved to the indicated location </td><td>  * Location - The URI of the newly created Statement <br>  </td></tr>
        <tr><td> 400 </td><td> The request cannot be processed </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 404 </td><td> The specified resource was not found </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 412 </td><td> The condition defined by a conditional request header is not fulfilled </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> An unexpected error has occurred </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
     </table>
     */
    public Map<String, AddItemRequestAllOfItemSitelinksValue> getSitelinks(String itemId, List<String> ifNoneMatch, String ifModifiedSince, List<String> ifMatch, String ifUnmodifiedSince, String authorization) throws ApiException {
        ApiResponse<Map<String, AddItemRequestAllOfItemSitelinksValue>> localVarResp = getSitelinksWithHttpInfo(itemId, ifNoneMatch, ifModifiedSince, ifMatch, ifUnmodifiedSince, authorization);
        return localVarResp.getData();
    }

    /**
     * Retrieve an Item&#39;s Sitelinks
     * 
     * @param itemId The ID of the required Item (required)
     * @param ifNoneMatch Conditionally perform the request only if the resource has been modified since the specified entity revision numbers (optional)
     * @param ifModifiedSince Conditionally perform the request only if the resource has been modified after the specified date (optional)
     * @param ifMatch Conditionally perform the request only if the resource has not been modified since one of the specified entity revision numbers (optional)
     * @param ifUnmodifiedSince Conditionally perform the request only if the resource has not been modified after the specified date (optional)
     * @param authorization Make authenticated request using a provided bearer token (optional)
     * @return ApiResponse&lt;Map&lt;String, AddItemRequestAllOfItemSitelinksValue&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of Sitelinks by Item id </td><td>  * ETag - Last entity revision number <br>  * Last-Modified - Last modified date <br>  * X-Authenticated-User - Optional username of the user making the request <br>  </td></tr>
        <tr><td> 304 </td><td> The specified resource has not been modified since last provided revision number or date </td><td>  * ETag - Last entity revision number <br>  </td></tr>
        <tr><td> 308 </td><td> The specified resource has permanently moved to the indicated location </td><td>  * Location - The URI of the newly created Statement <br>  </td></tr>
        <tr><td> 400 </td><td> The request cannot be processed </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 404 </td><td> The specified resource was not found </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 412 </td><td> The condition defined by a conditional request header is not fulfilled </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> An unexpected error has occurred </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
     </table>
     */
    public ApiResponse<Map<String, AddItemRequestAllOfItemSitelinksValue>> getSitelinksWithHttpInfo(String itemId, List<String> ifNoneMatch, String ifModifiedSince, List<String> ifMatch, String ifUnmodifiedSince, String authorization) throws ApiException {
        okhttp3.Call localVarCall = getSitelinksValidateBeforeCall(itemId, ifNoneMatch, ifModifiedSince, ifMatch, ifUnmodifiedSince, authorization, null);
        Type localVarReturnType = new TypeToken<Map<String, AddItemRequestAllOfItemSitelinksValue>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Retrieve an Item&#39;s Sitelinks (asynchronously)
     * 
     * @param itemId The ID of the required Item (required)
     * @param ifNoneMatch Conditionally perform the request only if the resource has been modified since the specified entity revision numbers (optional)
     * @param ifModifiedSince Conditionally perform the request only if the resource has been modified after the specified date (optional)
     * @param ifMatch Conditionally perform the request only if the resource has not been modified since one of the specified entity revision numbers (optional)
     * @param ifUnmodifiedSince Conditionally perform the request only if the resource has not been modified after the specified date (optional)
     * @param authorization Make authenticated request using a provided bearer token (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of Sitelinks by Item id </td><td>  * ETag - Last entity revision number <br>  * Last-Modified - Last modified date <br>  * X-Authenticated-User - Optional username of the user making the request <br>  </td></tr>
        <tr><td> 304 </td><td> The specified resource has not been modified since last provided revision number or date </td><td>  * ETag - Last entity revision number <br>  </td></tr>
        <tr><td> 308 </td><td> The specified resource has permanently moved to the indicated location </td><td>  * Location - The URI of the newly created Statement <br>  </td></tr>
        <tr><td> 400 </td><td> The request cannot be processed </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 404 </td><td> The specified resource was not found </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 412 </td><td> The condition defined by a conditional request header is not fulfilled </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> An unexpected error has occurred </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
     </table>
     */
    public okhttp3.Call getSitelinksAsync(String itemId, List<String> ifNoneMatch, String ifModifiedSince, List<String> ifMatch, String ifUnmodifiedSince, String authorization, final ApiCallback<Map<String, AddItemRequestAllOfItemSitelinksValue>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getSitelinksValidateBeforeCall(itemId, ifNoneMatch, ifModifiedSince, ifMatch, ifUnmodifiedSince, authorization, _callback);
        Type localVarReturnType = new TypeToken<Map<String, AddItemRequestAllOfItemSitelinksValue>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for patchSitelinks
     * @param itemId The ID of the required Item (required)
     * @param patchItemRequest  (required)
     * @param ifMatch Conditionally perform the request only if the resource has not been modified since one of the specified entity revision numbers (optional)
     * @param ifNoneMatch Conditionally perform the request only if the resource has been modified since the specified entity revision numbers (optional)
     * @param ifUnmodifiedSince Conditionally perform the request only if the resource has not been modified after the specified date (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of Sitelinks by Item id </td><td>  * ETag - Last entity revision number <br>  * Last-Modified - Last modified date <br>  * X-Authenticated-User - Optional username of the user making the request <br>  </td></tr>
        <tr><td> 400 </td><td> The provided JSON Patch request is invalid </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 403 </td><td> The access to resource was denied </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 404 </td><td> The specified resource was not found </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 409 </td><td> The provided JSON Patch cannot be applied </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 412 </td><td> The condition defined by a conditional request header is not fulfilled </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Applying the provided JSON Patch results in invalid Sitelinks </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 429 </td><td> Too many requests </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 500 </td><td> An unexpected error has occurred </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
     </table>
     */
    public okhttp3.Call patchSitelinksCall(String itemId, PatchItemRequest patchItemRequest, List<String> ifMatch, List<String> ifNoneMatch, String ifUnmodifiedSince, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = patchItemRequest;

        // create path and map variables
        String localVarPath = "/entities/items/{item_id}/sitelinks"
            .replace("{" + "item_id" + "}", localVarApiClient.escapeString(itemId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json-patch+json",
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (ifMatch != null) {
            localVarHeaderParams.put("If-Match", localVarApiClient.parameterToString(ifMatch));
        }


        if (ifNoneMatch != null) {
            localVarHeaderParams.put("If-None-Match", localVarApiClient.parameterToString(ifNoneMatch));
        }


        if (ifUnmodifiedSince != null) {
            localVarHeaderParams.put("If-Unmodified-Since", localVarApiClient.parameterToString(ifUnmodifiedSince));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call patchSitelinksValidateBeforeCall(String itemId, PatchItemRequest patchItemRequest, List<String> ifMatch, List<String> ifNoneMatch, String ifUnmodifiedSince, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'itemId' is set
        if (itemId == null) {
            throw new ApiException("Missing the required parameter 'itemId' when calling patchSitelinks(Async)");
        }

        // verify the required parameter 'patchItemRequest' is set
        if (patchItemRequest == null) {
            throw new ApiException("Missing the required parameter 'patchItemRequest' when calling patchSitelinks(Async)");
        }

        return patchSitelinksCall(itemId, patchItemRequest, ifMatch, ifNoneMatch, ifUnmodifiedSince, _callback);

    }

    /**
     * Change an Item&#39;s Sitelinks
     * 
     * @param itemId The ID of the required Item (required)
     * @param patchItemRequest  (required)
     * @param ifMatch Conditionally perform the request only if the resource has not been modified since one of the specified entity revision numbers (optional)
     * @param ifNoneMatch Conditionally perform the request only if the resource has been modified since the specified entity revision numbers (optional)
     * @param ifUnmodifiedSince Conditionally perform the request only if the resource has not been modified after the specified date (optional)
     * @return Map&lt;String, AddItemRequestAllOfItemSitelinksValue&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of Sitelinks by Item id </td><td>  * ETag - Last entity revision number <br>  * Last-Modified - Last modified date <br>  * X-Authenticated-User - Optional username of the user making the request <br>  </td></tr>
        <tr><td> 400 </td><td> The provided JSON Patch request is invalid </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 403 </td><td> The access to resource was denied </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 404 </td><td> The specified resource was not found </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 409 </td><td> The provided JSON Patch cannot be applied </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 412 </td><td> The condition defined by a conditional request header is not fulfilled </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Applying the provided JSON Patch results in invalid Sitelinks </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 429 </td><td> Too many requests </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 500 </td><td> An unexpected error has occurred </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
     </table>
     */
    public Map<String, AddItemRequestAllOfItemSitelinksValue> patchSitelinks(String itemId, PatchItemRequest patchItemRequest, List<String> ifMatch, List<String> ifNoneMatch, String ifUnmodifiedSince) throws ApiException {
        ApiResponse<Map<String, AddItemRequestAllOfItemSitelinksValue>> localVarResp = patchSitelinksWithHttpInfo(itemId, patchItemRequest, ifMatch, ifNoneMatch, ifUnmodifiedSince);
        return localVarResp.getData();
    }

    /**
     * Change an Item&#39;s Sitelinks
     * 
     * @param itemId The ID of the required Item (required)
     * @param patchItemRequest  (required)
     * @param ifMatch Conditionally perform the request only if the resource has not been modified since one of the specified entity revision numbers (optional)
     * @param ifNoneMatch Conditionally perform the request only if the resource has been modified since the specified entity revision numbers (optional)
     * @param ifUnmodifiedSince Conditionally perform the request only if the resource has not been modified after the specified date (optional)
     * @return ApiResponse&lt;Map&lt;String, AddItemRequestAllOfItemSitelinksValue&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of Sitelinks by Item id </td><td>  * ETag - Last entity revision number <br>  * Last-Modified - Last modified date <br>  * X-Authenticated-User - Optional username of the user making the request <br>  </td></tr>
        <tr><td> 400 </td><td> The provided JSON Patch request is invalid </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 403 </td><td> The access to resource was denied </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 404 </td><td> The specified resource was not found </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 409 </td><td> The provided JSON Patch cannot be applied </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 412 </td><td> The condition defined by a conditional request header is not fulfilled </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Applying the provided JSON Patch results in invalid Sitelinks </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 429 </td><td> Too many requests </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 500 </td><td> An unexpected error has occurred </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
     </table>
     */
    public ApiResponse<Map<String, AddItemRequestAllOfItemSitelinksValue>> patchSitelinksWithHttpInfo(String itemId, PatchItemRequest patchItemRequest, List<String> ifMatch, List<String> ifNoneMatch, String ifUnmodifiedSince) throws ApiException {
        okhttp3.Call localVarCall = patchSitelinksValidateBeforeCall(itemId, patchItemRequest, ifMatch, ifNoneMatch, ifUnmodifiedSince, null);
        Type localVarReturnType = new TypeToken<Map<String, AddItemRequestAllOfItemSitelinksValue>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Change an Item&#39;s Sitelinks (asynchronously)
     * 
     * @param itemId The ID of the required Item (required)
     * @param patchItemRequest  (required)
     * @param ifMatch Conditionally perform the request only if the resource has not been modified since one of the specified entity revision numbers (optional)
     * @param ifNoneMatch Conditionally perform the request only if the resource has been modified since the specified entity revision numbers (optional)
     * @param ifUnmodifiedSince Conditionally perform the request only if the resource has not been modified after the specified date (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of Sitelinks by Item id </td><td>  * ETag - Last entity revision number <br>  * Last-Modified - Last modified date <br>  * X-Authenticated-User - Optional username of the user making the request <br>  </td></tr>
        <tr><td> 400 </td><td> The provided JSON Patch request is invalid </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 403 </td><td> The access to resource was denied </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 404 </td><td> The specified resource was not found </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 409 </td><td> The provided JSON Patch cannot be applied </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 412 </td><td> The condition defined by a conditional request header is not fulfilled </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Applying the provided JSON Patch results in invalid Sitelinks </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 429 </td><td> Too many requests </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 500 </td><td> An unexpected error has occurred </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
     </table>
     */
    public okhttp3.Call patchSitelinksAsync(String itemId, PatchItemRequest patchItemRequest, List<String> ifMatch, List<String> ifNoneMatch, String ifUnmodifiedSince, final ApiCallback<Map<String, AddItemRequestAllOfItemSitelinksValue>> _callback) throws ApiException {

        okhttp3.Call localVarCall = patchSitelinksValidateBeforeCall(itemId, patchItemRequest, ifMatch, ifNoneMatch, ifUnmodifiedSince, _callback);
        Type localVarReturnType = new TypeToken<Map<String, AddItemRequestAllOfItemSitelinksValue>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for setSitelink
     * @param itemId The ID of the required Item (required)
     * @param siteId The ID of the required Site (required)
     * @param setSitelinkRequest Payload containing a Wikibase Sitelink object and edit metadata (required)
     * @param ifNoneMatch Conditionally perform the request only if the resource has been modified since the specified entity revision numbers (optional)
     * @param ifModifiedSince Conditionally perform the request only if the resource has been modified after the specified date (optional)
     * @param ifMatch Conditionally perform the request only if the resource has not been modified since one of the specified entity revision numbers (optional)
     * @param ifUnmodifiedSince Conditionally perform the request only if the resource has not been modified after the specified date (optional)
     * @param authorization Make authenticated request using a provided bearer token (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The updated Sitelink </td><td>  * ETag - Last entity revision number <br>  * Last-Modified - Last modified date <br>  * X-Authenticated-User - Optional username of the user making the request <br>  </td></tr>
        <tr><td> 201 </td><td> The newly added Sitelink </td><td>  * ETag - Last entity revision number <br>  * Last-Modified - Last modified date <br>  * X-Authenticated-User - Optional username of the user making the request <br>  </td></tr>
        <tr><td> 400 </td><td> The request cannot be processed </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 403 </td><td> The access to resource was denied </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 404 </td><td> The specified resource was not found </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 409 </td><td> The specified Item was redirected </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 412 </td><td> The condition defined by a conditional request header is not fulfilled </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The edit request violates data policy </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 429 </td><td> Too many requests </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 500 </td><td> An unexpected error has occurred </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
     </table>
     */
    public okhttp3.Call setSitelinkCall(String itemId, String siteId, SetSitelinkRequest setSitelinkRequest, List<String> ifNoneMatch, String ifModifiedSince, List<String> ifMatch, String ifUnmodifiedSince, String authorization, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = setSitelinkRequest;

        // create path and map variables
        String localVarPath = "/entities/items/{item_id}/sitelinks/{site_id}"
            .replace("{" + "item_id" + "}", localVarApiClient.escapeString(itemId.toString()))
            .replace("{" + "site_id" + "}", localVarApiClient.escapeString(siteId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (ifNoneMatch != null) {
            localVarHeaderParams.put("If-None-Match", localVarApiClient.parameterToString(ifNoneMatch));
        }


        if (ifModifiedSince != null) {
            localVarHeaderParams.put("If-Modified-Since", localVarApiClient.parameterToString(ifModifiedSince));
        }


        if (ifMatch != null) {
            localVarHeaderParams.put("If-Match", localVarApiClient.parameterToString(ifMatch));
        }


        if (ifUnmodifiedSince != null) {
            localVarHeaderParams.put("If-Unmodified-Since", localVarApiClient.parameterToString(ifUnmodifiedSince));
        }


        if (authorization != null) {
            localVarHeaderParams.put("Authorization", localVarApiClient.parameterToString(authorization));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call setSitelinkValidateBeforeCall(String itemId, String siteId, SetSitelinkRequest setSitelinkRequest, List<String> ifNoneMatch, String ifModifiedSince, List<String> ifMatch, String ifUnmodifiedSince, String authorization, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'itemId' is set
        if (itemId == null) {
            throw new ApiException("Missing the required parameter 'itemId' when calling setSitelink(Async)");
        }

        // verify the required parameter 'siteId' is set
        if (siteId == null) {
            throw new ApiException("Missing the required parameter 'siteId' when calling setSitelink(Async)");
        }

        // verify the required parameter 'setSitelinkRequest' is set
        if (setSitelinkRequest == null) {
            throw new ApiException("Missing the required parameter 'setSitelinkRequest' when calling setSitelink(Async)");
        }

        return setSitelinkCall(itemId, siteId, setSitelinkRequest, ifNoneMatch, ifModifiedSince, ifMatch, ifUnmodifiedSince, authorization, _callback);

    }

    /**
     * Add / Replace an Item&#39;s Sitelink
     * 
     * @param itemId The ID of the required Item (required)
     * @param siteId The ID of the required Site (required)
     * @param setSitelinkRequest Payload containing a Wikibase Sitelink object and edit metadata (required)
     * @param ifNoneMatch Conditionally perform the request only if the resource has been modified since the specified entity revision numbers (optional)
     * @param ifModifiedSince Conditionally perform the request only if the resource has been modified after the specified date (optional)
     * @param ifMatch Conditionally perform the request only if the resource has not been modified since one of the specified entity revision numbers (optional)
     * @param ifUnmodifiedSince Conditionally perform the request only if the resource has not been modified after the specified date (optional)
     * @param authorization Make authenticated request using a provided bearer token (optional)
     * @return AddItemRequestAllOfItemSitelinksValue
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The updated Sitelink </td><td>  * ETag - Last entity revision number <br>  * Last-Modified - Last modified date <br>  * X-Authenticated-User - Optional username of the user making the request <br>  </td></tr>
        <tr><td> 201 </td><td> The newly added Sitelink </td><td>  * ETag - Last entity revision number <br>  * Last-Modified - Last modified date <br>  * X-Authenticated-User - Optional username of the user making the request <br>  </td></tr>
        <tr><td> 400 </td><td> The request cannot be processed </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 403 </td><td> The access to resource was denied </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 404 </td><td> The specified resource was not found </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 409 </td><td> The specified Item was redirected </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 412 </td><td> The condition defined by a conditional request header is not fulfilled </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The edit request violates data policy </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 429 </td><td> Too many requests </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 500 </td><td> An unexpected error has occurred </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
     </table>
     */
    public AddItemRequestAllOfItemSitelinksValue setSitelink(String itemId, String siteId, SetSitelinkRequest setSitelinkRequest, List<String> ifNoneMatch, String ifModifiedSince, List<String> ifMatch, String ifUnmodifiedSince, String authorization) throws ApiException {
        ApiResponse<AddItemRequestAllOfItemSitelinksValue> localVarResp = setSitelinkWithHttpInfo(itemId, siteId, setSitelinkRequest, ifNoneMatch, ifModifiedSince, ifMatch, ifUnmodifiedSince, authorization);
        return localVarResp.getData();
    }

    /**
     * Add / Replace an Item&#39;s Sitelink
     * 
     * @param itemId The ID of the required Item (required)
     * @param siteId The ID of the required Site (required)
     * @param setSitelinkRequest Payload containing a Wikibase Sitelink object and edit metadata (required)
     * @param ifNoneMatch Conditionally perform the request only if the resource has been modified since the specified entity revision numbers (optional)
     * @param ifModifiedSince Conditionally perform the request only if the resource has been modified after the specified date (optional)
     * @param ifMatch Conditionally perform the request only if the resource has not been modified since one of the specified entity revision numbers (optional)
     * @param ifUnmodifiedSince Conditionally perform the request only if the resource has not been modified after the specified date (optional)
     * @param authorization Make authenticated request using a provided bearer token (optional)
     * @return ApiResponse&lt;AddItemRequestAllOfItemSitelinksValue&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The updated Sitelink </td><td>  * ETag - Last entity revision number <br>  * Last-Modified - Last modified date <br>  * X-Authenticated-User - Optional username of the user making the request <br>  </td></tr>
        <tr><td> 201 </td><td> The newly added Sitelink </td><td>  * ETag - Last entity revision number <br>  * Last-Modified - Last modified date <br>  * X-Authenticated-User - Optional username of the user making the request <br>  </td></tr>
        <tr><td> 400 </td><td> The request cannot be processed </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 403 </td><td> The access to resource was denied </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 404 </td><td> The specified resource was not found </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 409 </td><td> The specified Item was redirected </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 412 </td><td> The condition defined by a conditional request header is not fulfilled </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The edit request violates data policy </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 429 </td><td> Too many requests </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 500 </td><td> An unexpected error has occurred </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
     </table>
     */
    public ApiResponse<AddItemRequestAllOfItemSitelinksValue> setSitelinkWithHttpInfo(String itemId, String siteId, SetSitelinkRequest setSitelinkRequest, List<String> ifNoneMatch, String ifModifiedSince, List<String> ifMatch, String ifUnmodifiedSince, String authorization) throws ApiException {
        okhttp3.Call localVarCall = setSitelinkValidateBeforeCall(itemId, siteId, setSitelinkRequest, ifNoneMatch, ifModifiedSince, ifMatch, ifUnmodifiedSince, authorization, null);
        Type localVarReturnType = new TypeToken<AddItemRequestAllOfItemSitelinksValue>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Add / Replace an Item&#39;s Sitelink (asynchronously)
     * 
     * @param itemId The ID of the required Item (required)
     * @param siteId The ID of the required Site (required)
     * @param setSitelinkRequest Payload containing a Wikibase Sitelink object and edit metadata (required)
     * @param ifNoneMatch Conditionally perform the request only if the resource has been modified since the specified entity revision numbers (optional)
     * @param ifModifiedSince Conditionally perform the request only if the resource has been modified after the specified date (optional)
     * @param ifMatch Conditionally perform the request only if the resource has not been modified since one of the specified entity revision numbers (optional)
     * @param ifUnmodifiedSince Conditionally perform the request only if the resource has not been modified after the specified date (optional)
     * @param authorization Make authenticated request using a provided bearer token (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The updated Sitelink </td><td>  * ETag - Last entity revision number <br>  * Last-Modified - Last modified date <br>  * X-Authenticated-User - Optional username of the user making the request <br>  </td></tr>
        <tr><td> 201 </td><td> The newly added Sitelink </td><td>  * ETag - Last entity revision number <br>  * Last-Modified - Last modified date <br>  * X-Authenticated-User - Optional username of the user making the request <br>  </td></tr>
        <tr><td> 400 </td><td> The request cannot be processed </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 403 </td><td> The access to resource was denied </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 404 </td><td> The specified resource was not found </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 409 </td><td> The specified Item was redirected </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 412 </td><td> The condition defined by a conditional request header is not fulfilled </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> The edit request violates data policy </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 429 </td><td> Too many requests </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
        <tr><td> 500 </td><td> An unexpected error has occurred </td><td>  * Content-Language - Language code of the language in which error message is provided <br>  </td></tr>
     </table>
     */
    public okhttp3.Call setSitelinkAsync(String itemId, String siteId, SetSitelinkRequest setSitelinkRequest, List<String> ifNoneMatch, String ifModifiedSince, List<String> ifMatch, String ifUnmodifiedSince, String authorization, final ApiCallback<AddItemRequestAllOfItemSitelinksValue> _callback) throws ApiException {

        okhttp3.Call localVarCall = setSitelinkValidateBeforeCall(itemId, siteId, setSitelinkRequest, ifNoneMatch, ifModifiedSince, ifMatch, ifUnmodifiedSince, authorization, _callback);
        Type localVarReturnType = new TypeToken<AddItemRequestAllOfItemSitelinksValue>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
