/*
 * Wikibase REST API
 * OpenAPI definition of Wikibase REST API
 *
 * The version of the OpenAPI document: 1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dionext.wikibase.client.model;

import java.util.Objects;

import com.dionext.wikibase.client.JSON;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.util.HashSet;
import java.util.Map;
import java.util.Set;

/**
 * AddItemStatement201ResponseAllOfAllOfReferences
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-12-23T19:13:51.135774Z[Etc/UTC]", comments = "Generator version: 7.10.0")
public class AddItemStatement201ResponseAllOfAllOfReferences {
  public static final String SERIALIZED_NAME_PARTS = "parts";
  @SerializedName(SERIALIZED_NAME_PARTS)
  @javax.annotation.Nullable
  private Object parts = null;

  public AddItemStatement201ResponseAllOfAllOfReferences() {
  }

  public AddItemStatement201ResponseAllOfAllOfReferences parts(@javax.annotation.Nullable Object parts) {
    this.parts = parts;
    return this;
  }

  /**
   * Get parts
   * @return parts
   */
  @javax.annotation.Nullable
  public Object getParts() {
    return parts;
  }

  public void setParts(@javax.annotation.Nullable Object parts) {
    this.parts = parts;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddItemStatement201ResponseAllOfAllOfReferences addItemStatement201ResponseAllOfAllOfReferences = (AddItemStatement201ResponseAllOfAllOfReferences) o;
    return Objects.equals(this.parts, addItemStatement201ResponseAllOfAllOfReferences.parts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(parts);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddItemStatement201ResponseAllOfAllOfReferences {\n");
    sb.append("    parts: ").append(toIndentedString(parts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("parts");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("parts");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AddItemStatement201ResponseAllOfAllOfReferences
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AddItemStatement201ResponseAllOfAllOfReferences.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AddItemStatement201ResponseAllOfAllOfReferences is not found in the empty JSON string", AddItemStatement201ResponseAllOfAllOfReferences.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AddItemStatement201ResponseAllOfAllOfReferences.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AddItemStatement201ResponseAllOfAllOfReferences` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AddItemStatement201ResponseAllOfAllOfReferences.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AddItemStatement201ResponseAllOfAllOfReferences.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AddItemStatement201ResponseAllOfAllOfReferences' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AddItemStatement201ResponseAllOfAllOfReferences> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AddItemStatement201ResponseAllOfAllOfReferences.class));

       return (TypeAdapter<T>) new TypeAdapter<AddItemStatement201ResponseAllOfAllOfReferences>() {
           @Override
           public void write(JsonWriter out, AddItemStatement201ResponseAllOfAllOfReferences value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AddItemStatement201ResponseAllOfAllOfReferences read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AddItemStatement201ResponseAllOfAllOfReferences given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AddItemStatement201ResponseAllOfAllOfReferences
   * @throws IOException if the JSON string is invalid with respect to AddItemStatement201ResponseAllOfAllOfReferences
   */
  public static AddItemStatement201ResponseAllOfAllOfReferences fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AddItemStatement201ResponseAllOfAllOfReferences.class);
  }

  /**
   * Convert an instance of AddItemStatement201ResponseAllOfAllOfReferences to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

