/*
 * Wikibase REST API
 * OpenAPI definition of Wikibase REST API
 *
 * The version of the OpenAPI document: 1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dionext.wikibase.client.model;

import java.util.Objects;

import com.dionext.wikibase.client.JSON;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.util.HashSet;
import java.util.Map;
import java.util.Set;

/**
 * AddItemStatement201Response
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-12-23T19:13:51.135774Z[Etc/UTC]", comments = "Generator version: 7.10.0")
public class AddItemStatement201Response {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  /**
   * The rank of the Statement
   */
  @JsonAdapter(RankEnum.Adapter.class)
  public enum RankEnum {
    @JsonProperty("deprecated")
    DEPRECATED("deprecated"),

    @JsonProperty("normal")
    NORMAL("normal"),

    @JsonProperty("preferred")
    PREFERRED("preferred");

    private String value;

    RankEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static RankEnum fromValue(String value) {
      for (RankEnum b : RankEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<RankEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final RankEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public RankEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return RankEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      RankEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_RANK = "rank";
  @SerializedName(SERIALIZED_NAME_RANK)
  @javax.annotation.Nullable
  private RankEnum rank = RankEnum.NORMAL;

  public static final String SERIALIZED_NAME_PROPERTY = "property";
  @SerializedName(SERIALIZED_NAME_PROPERTY)
  @javax.annotation.Nullable
  private Object property = null;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  @javax.annotation.Nullable
  private Object value = null;

  public static final String SERIALIZED_NAME_QUALIFIERS = "qualifiers";
  @SerializedName(SERIALIZED_NAME_QUALIFIERS)
  @javax.annotation.Nullable
  private Object qualifiers = null;

  public static final String SERIALIZED_NAME_REFERENCES = "references";
  @SerializedName(SERIALIZED_NAME_REFERENCES)
  @javax.annotation.Nonnull
  private AddItemStatement201ResponseAllOfAllOfReferences references;

  public AddItemStatement201Response() {
  }

  public AddItemStatement201Response(
     String id
  ) {
    this();
    this.id = id;
  }

  /**
   * The globally unique identifier for this Statement
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }



  public AddItemStatement201Response rank(@javax.annotation.Nullable RankEnum rank) {
    this.rank = rank;
    return this;
  }

  /**
   * The rank of the Statement
   * @return rank
   */
  @javax.annotation.Nullable
  public RankEnum getRank() {
    return rank;
  }

  public void setRank(@javax.annotation.Nullable RankEnum rank) {
    this.rank = rank;
  }


  public AddItemStatement201Response property(@javax.annotation.Nullable Object property) {
    this.property = property;
    return this;
  }

  /**
   * Get property
   * @return property
   */
  @javax.annotation.Nullable
  public Object getProperty() {
    return property;
  }

  public void setProperty(@javax.annotation.Nullable Object property) {
    this.property = property;
  }


  public AddItemStatement201Response value(@javax.annotation.Nullable Object value) {
    this.value = value;
    return this;
  }

  /**
   * Get value
   * @return value
   */
  @javax.annotation.Nullable
  public Object getValue() {
    return value;
  }

  public void setValue(@javax.annotation.Nullable Object value) {
    this.value = value;
  }


  public AddItemStatement201Response qualifiers(@javax.annotation.Nullable Object qualifiers) {
    this.qualifiers = qualifiers;
    return this;
  }

  /**
   * Get qualifiers
   * @return qualifiers
   */
  @javax.annotation.Nullable
  public Object getQualifiers() {
    return qualifiers;
  }

  public void setQualifiers(@javax.annotation.Nullable Object qualifiers) {
    this.qualifiers = qualifiers;
  }


  public AddItemStatement201Response references(@javax.annotation.Nonnull AddItemStatement201ResponseAllOfAllOfReferences references) {
    this.references = references;
    return this;
  }

  /**
   * Get references
   * @return references
   */
  @javax.annotation.Nonnull
  public AddItemStatement201ResponseAllOfAllOfReferences getReferences() {
    return references;
  }

  public void setReferences(@javax.annotation.Nonnull AddItemStatement201ResponseAllOfAllOfReferences references) {
    this.references = references;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddItemStatement201Response addItemStatement201Response = (AddItemStatement201Response) o;
    return Objects.equals(this.id, addItemStatement201Response.id) &&
        Objects.equals(this.rank, addItemStatement201Response.rank) &&
        Objects.equals(this.property, addItemStatement201Response.property) &&
        Objects.equals(this.value, addItemStatement201Response.value) &&
        Objects.equals(this.qualifiers, addItemStatement201Response.qualifiers) &&
        Objects.equals(this.references, addItemStatement201Response.references);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, rank, property, value, qualifiers, references);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddItemStatement201Response {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    rank: ").append(toIndentedString(rank)).append("\n");
    sb.append("    property: ").append(toIndentedString(property)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    qualifiers: ").append(toIndentedString(qualifiers)).append("\n");
    sb.append("    references: ").append(toIndentedString(references)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("rank");
    openapiFields.add("property");
    openapiFields.add("value");
    openapiFields.add("qualifiers");
    openapiFields.add("references");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("property");
    openapiRequiredFields.add("value");
    openapiRequiredFields.add("qualifiers");
    openapiRequiredFields.add("references");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AddItemStatement201Response
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AddItemStatement201Response.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AddItemStatement201Response is not found in the empty JSON string", AddItemStatement201Response.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AddItemStatement201Response.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AddItemStatement201Response` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AddItemStatement201Response.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("rank") != null && !jsonObj.get("rank").isJsonNull()) && !jsonObj.get("rank").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `rank` to be a primitive type in the JSON string but got `%s`", jsonObj.get("rank").toString()));
      }
      // validate the optional field `rank`
      if (jsonObj.get("rank") != null && !jsonObj.get("rank").isJsonNull()) {
        RankEnum.validateJsonElement(jsonObj.get("rank"));
      }
      // validate the required field `references`
      AddItemStatement201ResponseAllOfAllOfReferences.validateJsonElement(jsonObj.get("references"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AddItemStatement201Response.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AddItemStatement201Response' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AddItemStatement201Response> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AddItemStatement201Response.class));

       return (TypeAdapter<T>) new TypeAdapter<AddItemStatement201Response>() {
           @Override
           public void write(JsonWriter out, AddItemStatement201Response value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AddItemStatement201Response read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AddItemStatement201Response given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AddItemStatement201Response
   * @throws IOException if the JSON string is invalid with respect to AddItemStatement201Response
   */
  public static AddItemStatement201Response fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AddItemStatement201Response.class);
  }

  /**
   * Convert an instance of AddItemStatement201Response to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

