/*
 * Wikibase REST API
 * OpenAPI definition of Wikibase REST API
 *
 * The version of the OpenAPI document: 1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dionext.wikibase.client.model;

import java.util.Objects;

import com.dionext.wikibase.client.JSON;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.util.HashSet;
import java.util.Map;
import java.util.Set;

/**
 * GetItemStatements200ResponseValueInnerAllOfAllOfReferences
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-12-23T19:13:51.135774Z[Etc/UTC]", comments = "Generator version: 7.10.0")
public class GetItemStatements200ResponseValueInnerAllOfAllOfReferences {
  public static final String SERIALIZED_NAME_PARTS = "parts";
  @SerializedName(SERIALIZED_NAME_PARTS)
  @javax.annotation.Nullable
  private Object parts = null;

  public GetItemStatements200ResponseValueInnerAllOfAllOfReferences() {
  }

  public GetItemStatements200ResponseValueInnerAllOfAllOfReferences parts(@javax.annotation.Nullable Object parts) {
    this.parts = parts;
    return this;
  }

  /**
   * Get parts
   * @return parts
   */
  @javax.annotation.Nullable
  public Object getParts() {
    return parts;
  }

  public void setParts(@javax.annotation.Nullable Object parts) {
    this.parts = parts;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetItemStatements200ResponseValueInnerAllOfAllOfReferences getItemStatements200ResponseValueInnerAllOfAllOfReferences = (GetItemStatements200ResponseValueInnerAllOfAllOfReferences) o;
    return Objects.equals(this.parts, getItemStatements200ResponseValueInnerAllOfAllOfReferences.parts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(parts);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetItemStatements200ResponseValueInnerAllOfAllOfReferences {\n");
    sb.append("    parts: ").append(toIndentedString(parts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("parts");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("parts");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetItemStatements200ResponseValueInnerAllOfAllOfReferences
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetItemStatements200ResponseValueInnerAllOfAllOfReferences.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetItemStatements200ResponseValueInnerAllOfAllOfReferences is not found in the empty JSON string", GetItemStatements200ResponseValueInnerAllOfAllOfReferences.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetItemStatements200ResponseValueInnerAllOfAllOfReferences.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetItemStatements200ResponseValueInnerAllOfAllOfReferences` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : GetItemStatements200ResponseValueInnerAllOfAllOfReferences.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetItemStatements200ResponseValueInnerAllOfAllOfReferences.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetItemStatements200ResponseValueInnerAllOfAllOfReferences' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetItemStatements200ResponseValueInnerAllOfAllOfReferences> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetItemStatements200ResponseValueInnerAllOfAllOfReferences.class));

       return (TypeAdapter<T>) new TypeAdapter<GetItemStatements200ResponseValueInnerAllOfAllOfReferences>() {
           @Override
           public void write(JsonWriter out, GetItemStatements200ResponseValueInnerAllOfAllOfReferences value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetItemStatements200ResponseValueInnerAllOfAllOfReferences read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetItemStatements200ResponseValueInnerAllOfAllOfReferences given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetItemStatements200ResponseValueInnerAllOfAllOfReferences
   * @throws IOException if the JSON string is invalid with respect to GetItemStatements200ResponseValueInnerAllOfAllOfReferences
   */
  public static GetItemStatements200ResponseValueInnerAllOfAllOfReferences fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetItemStatements200ResponseValueInnerAllOfAllOfReferences.class);
  }

  /**
   * Convert an instance of GetItemStatements200ResponseValueInnerAllOfAllOfReferences to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

